SELECT 
	DISTINCT ATENDIMENTO.[ID]
	,'UF' = CASE 
				WHEN UNIDADES.[UF] IS NOT NULL THEN UNIDADES.[UF]
				ELSE 'OUTROS'
			END
	,'DIRE' = CASE
				WHEN UNIDADES.[UF] IN ('RS', 'SC') THEN	'DIRE A'
				WHEN UNIDADES.[UF] IN ('MT', 'MS', 'PR') THEN	'DIRE B'
				WHEN UNIDADES.[UF] IN ('SP') THEN	'DIRE C e D'
				WHEN UNIDADES.[UF] IN ('DF', 'MG') THEN	'DIRE E'
				WHEN UNIDADES.[UF] IN ('EF', 'RJ') THEN	'DIRE F'
				WHEN UNIDADES.[UF] IN ('AM', 'RR', 'AP', 'PA', 'TO', 'RO', 'AC', 'GO') THEN	'DIRE G'
				WHEN UNIDADES.[UF] IN ('MA', 'PI', 'CE', 'RN', 'PB', 'PE', 'AL', 'SE', 'BA')  THEN	'DIRE H'
				ELSE 'OUTROS'
			END
FROM 
	[tbl_ATENDIMENTO_WEB_REGISTRO_ATENDIMENTO] AS ATENDIMENTO
	LEFT JOIN [tbl_UNIDADES_DIRE] AS UNIDADES ON 
	ATENDIMENTO.[UNIDADE_DEMANDANTE] = UNIDADES.[CD_AG]
	OR ATENDIMENTO.[UNIDADE_DEMANDANTE] = UNIDADES.[CD_SR]
ORDER BY 
	ATENDIMENTO.[ID]