/****** Script for SelectTopNRows command from SSMS  ******/
DECLARE @MES_ANTERIOR AS INT
DECLARE @PERIODO_INICIAL AS DATETIME

SET @MES_ANTERIOR = DATEPART(MONTH, DATEADD(MONTH, -2, GETDATE()))

SET @PERIODO_INICIAL = CASE @MES_ANTERIOR 
							WHEN 10 THEN CONVERT(DATETIME, CONCAT(DATEPART(YEAR, DATEADD(YEAR, -1, GETDATE())), '-', RIGHT('0' + RTRIM(DATEPART(MONTH, DATEADD(MONTH, -3, GETDATE()))), 2), '-', '01', ' ', '00:00:00'), 120)
							WHEN 11 THEN CONVERT(DATETIME, CONCAT(DATEPART(YEAR, DATEADD(YEAR, -1, GETDATE())), '-', RIGHT('0' + RTRIM(DATEPART(MONTH, DATEADD(MONTH, -2, GETDATE()))), 2), '-', '01', ' ', '00:00:00'), 120)
							WHEN 12 THEN CONVERT(DATETIME, CONCAT(DATEPART(YEAR, DATEADD(YEAR, -1, GETDATE())), '-', RIGHT('0' + RTRIM(DATEPART(MONTH, DATEADD(MONTH, -1, GETDATE()))), 2), '-', '01', ' ', '00:00:00'), 120)
							ELSE GETDATE()
						END
-- Essa query faz o levantamento de pesquisas enviadas e respondidas nos ultimos três meses
SELECT 
	'MÊS' = RIGHT('0' + RTRIM(DATEPART(MONTH,[DATA_ENVIO])), 2)
	,'MATRICULA' = ATENDIMENTO.[MATRICULA_CEOPC]
	,'NOME' = EMPREGADOS.[NOME]
	,'PESQUISAS_ENVIADAS' = COUNT(PESQUISAS.[DATA_ENVIO])
    ,'PESQUISAS_RESPONDIDAS' = COUNT(PESQUISAS.[DATA_RESPOSTA])
	,'MÉDIA_CORDIALIDADE' = AVG(CONVERT(FLOAT,PESQUISAS.[NOTA_CORDIALIDADE]))
	,'MÉDIA_DOMÍNIO' = AVG(CONVERT(FLOAT,PESQUISAS.[NOTA_DOMINIO]))
	,'MÉDIA_TESPESTIVIDADE' = AVG(CONVERT(FLOAT,PESQUISAS.[NOTA_TEMPESTIVIDADE]))
FROM 
	[tbl_ATENDIMENTO_WEB_REGISTRO_PESQUISAS] AS PESQUISAS
	INNER JOIN tbl_ATENDIMENTO_WEB_REGISTRO_ATENDIMENTO AS ATENDIMENTO ON PESQUISAS.[ID_REGISTRO_ATENDIMENTO] = ATENDIMENTO.[ID]
	LEFT JOIN [EMPREGADOS] AS EMPREGADOS ON CONVERT(BIGINT,REPLACE(ATENDIMENTO.MATRICULA_CEOPC, 'c', '')) = EMPREGADOS.[MATRICULA]
WHERE
	[DATA_ENVIO] >= @PERIODO_INICIAL
GROUP BY 
	DATEPART(MONTH, PESQUISAS.[DATA_ENVIO])
	,ATENDIMENTO.[MATRICULA_CEOPC]
	,EMPREGADOS.[NOME]